#!/bin/bash
#Takes arguments
#  - $1 is list of examples

cd golden_run
mvn clean install
cd ..

cd revised_run
mvn clean install
cd ..

./golden_vs_revised_run $1
echo "= * = * = * = * = * = * = * = * = * = * = * = *= * = * = * = * = * = * = * = * = * = * = * = * * = * = * = * = * = *"
echo "WAITING FOR RUNS TO COMPLETE........."
echo ""
echo ""
./then_RUN_me $1
