#!/bin/bash
#Takes arguments
#  - $1 is dir for example repo
#  - $2 is dir you want to write results too
#  - $3 is list of examples


#USAGE: ./snapshot_vs_golden_run dl4j-golden-examples golden_results list_of_ex


mkdir -p $2
cd $1
#for i in `find`; do
while read i; do
    example_name_class=`echo $i | perl -pe 's/.*(org.deeplearning)/$1/;s/\//./g;s/\.java$//'`
    example_results_file=`echo $example_name_class | awk -F '.' '{print $NF}'`
    mvn -X exec:java -Dexec.mainClass=$example_name_class > ../$2/$example_results_file &
done < ../$3
